// File generated by the FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

/// Default `FirebaseOptions` for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ignore: unused_import
/// import 'package:firebase_core/firebase_core.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADxnj...',
    appId: '1:...:web:...',
    messagingSenderId: '...',
    projectId: 'wearsync-28d30',
    authDomain: 'wearsync-28d30.firebaseapp.com',
    databaseURL: 'https://wearsync-28d30.firebaseio.com',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
    measurementId: 'G-...',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADxnj...',
    appId: '1:...:android:...',
    messagingSenderId: '...',
    projectId: 'wearsync-28d30',
    databaseURL: 'https://wearsync-28d30.firebaseio.com',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_vcYLmnoKokrqM3xIyWZ3oY4mAeBHu8o',
    appId: '1:768914772567:ios:14b3268e4e33c59f32c912',
    messagingSenderId: '768914772567',
    projectId: 'wearsync-28d30',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
    iosBundleId: 'com.example.smartwearAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADxnj...',
    appId: '1:...:ios:...',
    messagingSenderId: '...',
    projectId: 'wearsync-28d30',
    databaseURL: 'https://wearsync-28d30.firebaseio.com',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
    iosClientId: '....iosapp.gstatic.com',
    iosBundleId: 'com.example.smartwear.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADxnj...',
    appId: '1:...:windows:...',
    messagingSenderId: '...',
    projectId: 'wearsync-28d30',
    authDomain: 'wearsync-28d30.firebaseapp.com',
    databaseURL: 'https://wearsync-28d30.firebaseio.com',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyADxnj...',
    appId: '1:...:linux:...',
    messagingSenderId: '...',
    projectId: 'wearsync-28d30',
    authDomain: 'wearsync-28d30.firebaseapp.com',
    databaseURL: 'https://wearsync-28d30.firebaseio.com',
    storageBucket: 'wearsync-28d30.firebasestorage.app',
  );
}